// <auto-generated />
namespace CRMWinApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CRMModel21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CRMModel21));
        
        string IMigrationMetadata.Id
        {
            get { return "201412111330268_CRMModel21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
