// <auto-generated />
namespace CRMWinApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CRMDataModel12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CRMDataModel12));
        
        string IMigrationMetadata.Id
        {
            get { return "201412211334432_CRMDataModel12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
